import { assertEquals } from "https://deno.land/std@0.167.0/testing/asserts.ts";
import { part1, part2 } from "./2025-07.ts";

const exampleInput = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`.trim();

const realInput = await Deno.readTextFile(
  `${import.meta.dirname}/2025-07.input.txt`,
);

Deno.test("2025 Day 07 Part 1 - Example Input", () => {
  assertEquals(part1(exampleInput), 21);
});

Deno.test("2025 Day 07 Part 1 - Real Input", () => {
  assertEquals(part1(realInput), 1656);
});

Deno.test("2025 Day 07 Part 2 - Example Input", () => {
  assertEquals(part2(exampleInput), 40);
});

Deno.test("2025 Day 07 Part 2 - Real Input", () => {
  assertEquals(part2(realInput), 76624086587804);
});
